image: Visual Studio 2017

before_build:
  - nuget restore -DisableParallelProcessing
  
build_script:
  - msbuild CoiniumServ.sln

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache

