image: Visual Studio 2017

before_build:
  - nuget restore -DisableParallelProcessing
  
build_script:
  - msbuild CoiniumServ.sln

artifacts:
  - path: build\bin\Debug
    name: CoiniumServ-0.2.6.3

